package org.nanotate.ui.components;

import org.vaadin.csvalidation.CSValidator;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class TweetComposer extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private TextArea textArea_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TweetComposer() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		CSValidator validator = new CSValidator();
		validator.extend(textArea_1);
		validator.setJavaScript("var maxvalue = 20;\n" +
		                      "var charsleft = maxvalue - value.length;\n" +
		                      "var result = null;\n" +
		                      "if (charsleft > 0)\n" +
		                      "    result = \"valid \" + value.length + \" of \" + maxvalue;\n" +
		                      "else\n" +
		                      "    result = \"\" + value.length + \" of \" + maxvalue;\n" +
		                      "result;");
	

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("400px");
		mainLayout.setHeight("250px");
		
		// top-level component properties
		setWidth("400px");
		setHeight("250px");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		panel_1.setContent(verticalLayout_1);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("300px");
		textArea_1.setHeight("150px");
		verticalLayout_1.addComponent(textArea_1);
		verticalLayout_1.setComponentAlignment(textArea_1, new Alignment(48));
		
		return verticalLayout_1;
	}

}
