package org.nanotate.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class Main extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel main_panel;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Panel lateral_menu;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_5;
	@AutoGenerated
	private VerticalLayout nav;
	@AutoGenerated
	private Panel docsButton;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Panel side_header;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Label username;
	@AutoGenerated
	private Embedded embedded_1;
	/**
	 * 
	 */
	private static final long serialVersionUID = -5452071878309290642L;
	public static final String NAME = "main";
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Main() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// lateral_menu
		lateral_menu = buildLateral_menu();
		mainLayout.addComponent(lateral_menu, "top:0.0px;");
		
		// main_panel
		main_panel = buildMain_panel();
		mainLayout.addComponent(main_panel,
				"top:0.0px;right:0.0px;bottom:0.0px;left:200.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildLateral_menu() {
		// common part: create layout
		lateral_menu = new Panel();
		lateral_menu.setStyleName("lateralmenu");
		lateral_menu.setImmediate(false);
		lateral_menu.setWidth("200px");
		lateral_menu.setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		lateral_menu.setContent(verticalLayout_1);
		
		return lateral_menu;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// side_header
		side_header = buildSide_header();
		verticalLayout_1.addComponent(side_header);
		
		// nav
		nav = buildNav();
		verticalLayout_1.addComponent(nav);
		verticalLayout_1.setComponentAlignment(nav, new Alignment(20));
		
		// panel_1
		panel_1 = buildPanel_1();
		verticalLayout_1.addComponent(panel_1);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private Panel buildSide_header() {
		// common part: create layout
		side_header = new Panel();
		side_header.setImmediate(false);
		side_header.setWidth("100.0%");
		side_header.setHeight("100px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		side_header.setContent(horizontalLayout_1);
		
		return side_header;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// embedded_1
		embedded_1 = new Embedded();
		embedded_1.setImmediate(false);
		embedded_1.setWidth("-1px");
		embedded_1.setHeight("-1px");
		embedded_1.setSource(new ThemeResource(
				"img/component/embedded_icon.png"));
		embedded_1.setType(1);
		embedded_1.setMimeType("image/png");
		horizontalLayout_1.addComponent(embedded_1);
		horizontalLayout_1.setComponentAlignment(embedded_1, new Alignment(33));
		
		// username
		username = new Label();
		username.setImmediate(false);
		username.setWidth("-1px");
		username.setHeight("-1px");
		username.setValue("User name");
		horizontalLayout_1.addComponent(username);
		horizontalLayout_1.setComponentAlignment(username, new Alignment(33));
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildNav() {
		// common part: create layout
		nav = new VerticalLayout();
		nav.setImmediate(false);
		nav.setWidth("100.0%");
		nav.setHeight("-1px");
		nav.setMargin(false);
		
		// docsButton
		docsButton = buildDocsButton();
		nav.addComponent(docsButton);
		
		return nav;
	}

	@AutoGenerated
	private Panel buildDocsButton() {
		// common part: create layout
		docsButton = new Panel();
		docsButton.setStyleName("button-side-nav");
		docsButton.setImmediate(false);
		docsButton.setWidth("100.0%");
		docsButton.setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		docsButton.setContent(verticalLayout_2);
		
		return docsButton;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100px");
		
		// verticalLayout_5
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("100.0%");
		verticalLayout_5.setHeight("100.0%");
		verticalLayout_5.setMargin(false);
		panel_1.setContent(verticalLayout_5);
		
		return panel_1;
	}

	@AutoGenerated
	private Panel buildMain_panel() {
		// common part: create layout
		main_panel = new Panel();
		main_panel.setStyleName("mainpanel");
		main_panel.setImmediate(false);
		main_panel.setWidth("100.0%");
		main_panel.setHeight("100.0%");
		
		// verticalLayout_3
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(false);
		main_panel.setContent(verticalLayout_3);
		
		return main_panel;
	}

}
